<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Slim' => array($vendorDir . '/slim/slim'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Illuminate\\Support' => array($vendorDir . '/illuminate/support'),
    'Illuminate\\Log' => array($vendorDir . '/illuminate/log'),
);
